package com.alessio.baseproject.database.sql.dao.mapper;

import com.alessio.baseproject.database.rawmodel.CardEntity;
import com.alessio.baseproject.database.rawmodel.CardEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CardEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    long countByExample(CardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int deleteByExample(CardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int insert(CardEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int insertSelective(CardEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    List<CardEntity> selectByExampleWithRowbounds(CardEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    List<CardEntity> selectByExample(CardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    CardEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CardEntity record, @Param("example") CardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CardEntity record, @Param("example") CardEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CardEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CardEntity record);
}