package com.alessio.baseproject.database.rawmodel;

import org.joda.time.DateTime;

public class UserEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utenti.utenti_id
     *
     * @mbg.generated
     */
    private String utentiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utenti.creation_date
     *
     * @mbg.generated
     */
    private DateTime creationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utenti.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utenti.utenti_id
     *
     * @return the value of utenti.utenti_id
     *
     * @mbg.generated
     */
    public String getUtentiId() {
        return utentiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utenti.utenti_id
     *
     * @param utentiId the value for utenti.utenti_id
     *
     * @mbg.generated
     */
    public void setUtentiId(String utentiId) {
        this.utentiId = utentiId == null ? null : utentiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utenti.creation_date
     *
     * @return the value of utenti.creation_date
     *
     * @mbg.generated
     */
    public DateTime getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utenti.creation_date
     *
     * @param creationDate the value for utenti.creation_date
     *
     * @mbg.generated
     */
    public void setCreationDate(DateTime creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column utenti.name
     *
     * @return the value of utenti.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column utenti.name
     *
     * @param name the value for utenti.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}